### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by chris-sanchez** [wileyyugioh/kissanime_dl#1]
getting this error on the urls

`Platform: Darwin
Python Version: 3
Waiting for authentication...
Should take about 4 seconds
Success!
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-447?id=122394
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-362?id=100641
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-276?id=100558
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-186?id=100473
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-092?id=100388
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-446?id=122275
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-361?id=100640
You may have to open a browser and manually verify capcha
Failed to grab url at https://kissanime.to/Anime/Naruto-Shippuuden/Episode-275?id=100557
You may have to open a browser and manually verify capcha`

Any fix on this ?

**Comment by wileyyugioh** [comment]
This is caused when kissanime.to requires a capcha to proceed. The message is to warn users to manually connect to kissanime.to via browser and verify the capcha, as it is based on ip.

**Comment by edwardsdean** [comment]
I think it might also be caused by one of the moduals being outdated, run the updates modals script should help
