### ISSUE TITLE
Capcha on KissAsian and KissCartoon after approx 5 requests

### ISSUE THREAD

**Issue by wileyyugioh** [wileyyugioh/kissanime_dl#10]
Creating an issue until this problem is solved. Something I am currently looking into is making a new session every 5, but I think it is by ip instead of cookies.

**Comment by 7IXKTUIV1** [comment]
Hello sorry for closing and opening the previous post, its my first time using this website. Can u check the JS error for Linux users? I really love your script and use it daily. Thanks.

**Comment by wileyyugioh** [comment]
I am currently looking into it in the other thread.

**Comment by hex007** [comment]
If it is IP based and tracked on the Server side I don't think there is anything that can be done. Have you ever faced this capcha? A picture would help what kind of capcha used

**Comment by wileyyugioh** [comment]
It is google's recapcha, so writing a script to bypass it is too much effort.

**Comment by hex007** [comment]
Ok so I tested with some and reducing the number of threads helps. 6 episodes are downloaded before i start seeing `Failed to find url. You may have to check capcha, or KissAnime may have changed video host.` 

**Solution:**
So reducing the number of threads might be a solution. The program can start with a pool of download urls (todo list). Then threads created dynamically per url can checkout url from todo list (size N). Once error is encountered in X threads, they add back the urls into the pool. if downloaded successfully (Y threads) the threads can start with another urls from the pool. Like a semaphore, so it can dynamically adjust to restrictions. 

Even if multiple threads are specified/requested, eventually  you will end up with the best case of Y threads for download. See the diagram

![img_20160715_190520-01](https://cloud.githubusercontent.com/assets/1689246/16892170/801d904e-4abf-11e6-833a-4804639932c2.jpeg)

**Comment by wileyyugioh** [comment]
Each thread uses the same session, so from the server stand point it looks like one client is sending all these requests. Just because one thread was able to complete a request without triggering the captcha does not guarantee it can happen again.

**Comment by hex007** [comment]
well once one thread is done it can move on to another video as if the user is finished with one video and watching another. So if 6 files can be downloaded in a single session then the seventh will start after one of the six is done. Thus at any given time there will be maximum of six connections. 

Can this approach be tested?

**Comment by wileyyugioh** [comment]
~~I tested this approach with the https://github.com/wileyyugioh/kissanime_dl/tree/captcha branch and still get captcha errors.~~

Nevermind, the captcha only happened on one thread. The update should go live after a little more testing.

**Comment by hex007** [comment]
So it worked? Can you provide some details about the approach used.

**Comment by wileyyugioh** [comment]
Basically I followed the approach hex007 outlined earlier in this thread. I created a set amount of threads (5) that pulled from a pool of urls and downloaded the video. If a thread encounters captcha, it returns. After one video is downloaded, the completed thread draws from the pool again and repeats until the pool is empty. Check out the latest commit on master for the source.
