### ISSUE TITLE
WARNING: yacc table file version is out of date

### ISSUE THREAD

**Issue by hex007** [wileyyugioh/kissanime_dl#13]
I am getting this message and in every folder i run there are two files generated `lextab.py` and `yacctab.py`

```
WARNING: yacc table file version is out of date
```

**Comment by wileyyugioh** [comment]
Do you happen to have python lex-yacc installed? It seems to be what is generating those files.

**Comment by hex007** [comment]
No. I haven't installed it

`Cannot uninstall requirement lex-yacc, not installed`

**Comment by hex007** [comment]
The package is ply. I have uninstalled it now
