### ISSUE TITLE
Conforming to PEP8 

### ISSUE THREAD

**Issue by hex007** [wileyyugioh/kissanime_dl#15]
@wileyyugioh Should I reformat the code conforming to PEP8?

**Comment by wileyyugioh** [comment]
By all means go ahead. Make a pull request and I'll likely merge it.

**Comment by wileyyugioh** [comment]
https://github.com/wileyyugioh/kissanime_dl/commit/1030f164b772f43d04ec7ffe99e6778b87ebbc8b fixes this enhancement
