### ISSUE TITLE
Unable to locate package libgmp3c2

### ISSUE THREAD

**Issue by jelabarre59** [wileyyugioh/kissanime_dl#17]
Under LinuxMint 18 (Ubuntu 16.04), cannot complete the "sudo apt-get install python-setuptools libxslt1-dev python-dev zlib1g-dev build-essential libgmp3c2 pypy-dev" line, because it can't find libgmp3c2.  Hat to try the alternative commands, because I couldn't get the python/pip setup to work for installing this utility either.

**Comment by wileyyugioh** [comment]
It seems libgmp3c2 has been removed from the Ubuntu packages. Try replacing it with libgmp10.

**Comment by wileyyugioh** [comment]
The Linux build steps should be fixed in https://github.com/wileyyugioh/kissanime_dl/commit/4f0172b556b137bb1839eb842fb843c373c7f8ab

**Comment by jelabarre59** [comment]
Changes worked for me, tested on Mint18 as above.
