### ISSUE TITLE
KissAsian, can't choose the episode.

### ISSUE THREAD

**Issue by super94i** [wileyyugioh/kissanime_dl#20]
sample:
------------------------
user@debian:~/AnimeDownloads$ kissanime-dl "http://kissasian.com/Drama/W-Two-Worlds" . --episode=8
Platform: Linux
Python Version: 2
Program Version: 1.9.2
Checking for updates
Requirement already up-to-date: kissanime_dl in /usr/local/lib/python2.7/dist-packages
Warning: Version 1.9.0 and above uses a new method to download movies. It may be slower, but should still download everything.
Use the --legacy flag (not guaranteed to work!) if you want the old method.
Waiting for authentication...
Should take about 4 seconds
Success!
Episode-008 is not a valid episode

----------
It says episode 8 is not a valid episode, but it actually exists.

**Comment by super94i** [comment]
update: the link of kissasian above has 10 episodes. I tried this, I think it has more meaning know.
------------
user@debian:~/AnimeDownloads$ kissanime-dl "http://kissasian.com/Drama/W-Two-Worlds" . --txtlinks
Platform: Linux
Python Version: 2
Program Version: 1.9.2
Checking for updates
Requirement already up-to-date: kissanime_dl in /usr/local/lib/python2.7/dist-packages
Warning: Version 1.9.0 and above uses a new method to download movies. It may be slower, but should still download everything.
Use the --legacy flag (not guaranteed to work!) if you want the old method.
Waiting for authentication...
Should take about 4 seconds
Success!
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Failed to find url. You may have to check capcha, or KissAnime may have changed video host.
Finished grabbing download links
Found 0 links
Elapsed time: 0:00:12.541848
user@debian:~/AnimeDownloads$ 
---------

**Comment by wileyyugioh** [comment]
Yeah, kissasian episode selecting is kind of broken. What the script checks for is the episode number in the url. In Kissanime the format is '008' but on Kissasian it's '8'. I'll probably fix this in the future.

**Comment by wileyyugioh** [comment]
Should be fixed in https://github.com/wileyyugioh/kissanime_dl/commit/d41b90c0c6a870b2ec476b59dce07975e8abec95

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!

**Comment by hex007** [comment]
Why do you want all your issues deleted?
