### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ThatLurker** [wileyyugioh/kissanime_dl#24]
could you add an auto renaming, because most of the anime are named with only numbers and afte downloading you wont know which is which.

**Comment by ChiselTip** [comment]
I've noticed the same file name inconsistencies, more so on kisscartoon though. 

In the cases where the names are, for all intents and purposes, gibberish I've taken to changing line 134 of`__init__.py` from:

`dl_name = cVunicode(url[NAME])`

to: 

```
#dl_name = cVunicode(url[NAME])
dl_name = cVunicode(url[2].split('/')[-1].split('?')[0])
```

which writes the file to whatever is in the URL after the last slash but before the question mark. Sometimes it writes out a helpful "Episode-001-(name of episode).mp4" and others it's more generic "Episode-001.mp4". So long as everything is being written to an appropriately named parent directory, I don't care so much about every first episode being named, "Episode-001" regardless of the series. 

I don't like this solution enough to leave it in permanently. I just enable or disable it depending on how badly things are mangled.

**Comment by wileyyugioh** [comment]
I'll probably add a flag that will either implement the workaround above or use the old method of naming. Maybe also add a test flag that will give an example of the filename before the download.

**Comment by wileyyugioh** [comment]
Should be added in https://github.com/wileyyugioh/kissanime_dl/commit/f13153f58d47372be2cb9ab226270eb08a319dbc. I want people to try it out before I release it on the pypi channel.

**Comment by ChiselTip** [comment]
Just tested `--autogen` with a few series on kisscartoon and kissanime with known, problematic file naming. In the examples below, both files are the same episode. One was started with `--autogen`, the other without. The results look good. 

kisscartoon:

```
 ll Daria/
total 752K
drwxr-xr-x 2 pi pi 4.0K Nov  2 07:20 .
drwxr-xr-x 4 pi pi  12K Nov  2 07:25 ..
-rw-r--r-- 1 pi pi 448K Nov  2 07:19 16795-167951442035382_1469312259.mp4.mp4
-rw-r--r-- 1 pi pi 288K Nov  2 07:20 Season-05-Episode-14-Is-It-College-Yet.mp4
```

kissanime:

```
ll Tiger-Bunny/
total 39M
drwxr-xr-x 2 pi pi 4.0K Nov  2 07:37 .
drwxr-xr-x 4 pi pi  12K Nov  2 07:25 ..
-rw-r--r-- 1 pi pi  38M Nov  2 07:37 [DeadFish]Tiger.mp4
-rw-r--r-- 1 pi pi 544K Nov  2 07:37 Episode-025.mp4
```

Oddly enough, in the kissanime example, every file in the series was named `[DeadFish]Tiger.mp4`. The download would finish and simply overwrite the file with the next episode.

**Comment by wileyyugioh** [comment]
Basically without the autogen flag the filename is stripped from the html below the video player. In the case of Tiger Bunny every filename is named [DeadFish]Tiger which results in all the files being named the same thing when run without autogen.

**Comment by wileyyugioh** [comment]
Closing because pushing the newest version to live.
