### ISSUE TITLE
No issue just a question

### ISSUE THREAD

**Issue by edwardsdean** [wileyyugioh/kissanime_dl#27]
Hi I've been making my own version of this for a while. I was wondering if i would be about to use your way of getting the urls/decrypting them in my code.

**Comment by wileyyugioh** [comment]
> if i would be about to use your way of getting the urls/decrypting them in my code.

I'm sorry? If you want to borrow from the source the code base is all licensed under a MIT license so just follow the terms and you'll be fine.

**Comment by edwardsdean** [comment]
Ok thanks. I mean the way that you get the video urls.

**Comment by wileyyugioh** [comment]
Closing due to the question being answered.
