### ISSUE TITLE
Installing Issues

### ISSUE THREAD

**Issue by josephsurin** [wileyyugioh/kissanime_dl#3]
I've followed all the instructions on how to install, but when I type kissanime-dl into cmd it says 

'kissanime-dl' is not recognized as an internal or external command,
operable program or batch file.

Am I doing something wrong? Please help me, thanks !

**Comment by wileyyugioh** [comment]
Can you give me some specs? What version of python are you using, and what is the OS? Can you also tell me the exact commands you are typing into the console?

**Comment by wileyyugioh** [comment]
closing due to long inactivity.
