### ISSUE TITLE
CloudFlare JS error

### ISSUE THREAD

**Issue by super94i** [wileyyugioh/kissanime_dl#9]
Error details:

Uh oh, an error occurred.
Go to https://github.com/wileyyugioh/kissanime_dl to report bugs.
Caught Error: RuntimeError('Converting the CloudFlare JS has changed!',)

**Comment by hex007** [comment]
@super94i  Kissanime's JS is screwed currently. Haven't been able to reach the home page. Gets stuck in Loading loop due to JS. Are you able to open the home page?

**Comment by super94i** [comment]
@hex007 no I can't do anything.

**Comment by wileyyugioh** [comment]
it currently works on my osx machine, so closing for now.

**Comment by hex007** [comment]
@wileyyugioh Doesn't work on firefox on linux. Can someone confirm status from windows? Premature to close it

**Comment by super94i** [comment]
I closed it by mistake.

**Comment by super94i** [comment]
http://pastebin.com/5W7s1rT9 this is the error i'm getting right now.

**Comment by wileyyugioh** [comment]
#11 is solved, so closing.

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!
